/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Oso_app;

/**
 *
 * @author rizki
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        Master = new javax.swing.JMenu();
        mnProduk = new javax.swing.JMenuItem();
        mnPegawai = new javax.swing.JMenuItem();
        mnSupplier = new javax.swing.JMenuItem();
        mnKategori = new javax.swing.JMenuItem();
        mnPesanan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        File.setText("File");

        mnLogout.setText("LogOut");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        File.add(mnLogout);

        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        File.add(mnKeluar);

        jMenuBar1.add(File);

        Master.setText("Edit");

        mnProduk.setText("Produk");
        mnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProdukActionPerformed(evt);
            }
        });
        Master.add(mnProduk);

        mnPegawai.setText("Pegawai");
        mnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPegawaiActionPerformed(evt);
            }
        });
        Master.add(mnPegawai);

        mnSupplier.setText("Supplier");
        mnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSupplierActionPerformed(evt);
            }
        });
        Master.add(mnSupplier);

        mnKategori.setText("Kategori");
        mnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKategoriActionPerformed(evt);
            }
        });
        Master.add(mnKategori);

        jMenuBar1.add(Master);

        mnPesanan.setText("Pesanan");
        mnPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnPesananMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnPesanan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Form_Login Login = new Form_Login();
        Login.setLocationRelativeTo(null);
        Login.setVisible(true);
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProdukActionPerformed
        // TODO add your handling code here:
        Form_Produk produk = new Form_Produk();
        produk.setLocationRelativeTo(null);
        produk.setVisible(true);
    }//GEN-LAST:event_mnProdukActionPerformed

    private void mnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPegawaiActionPerformed
        // TODO add your handling code here:
        Form_Pegawai pegawai = new Form_Pegawai();
        pegawai.setLocationRelativeTo(null);
        pegawai.setVisible(true);
    }//GEN-LAST:event_mnPegawaiActionPerformed

    private void mnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSupplierActionPerformed
        // TODO add your handling code here:
        Form_Supplier supplier = new Form_Supplier();
        supplier.setLocationRelativeTo(null);
        supplier.setVisible(true);
    }//GEN-LAST:event_mnSupplierActionPerformed

    private void mnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKategoriActionPerformed
        // TODO add your handling code here:
        Form_Kategori kategori = new Form_Kategori();
        kategori.setLocationRelativeTo(null);
        kategori.setVisible(true);
    }//GEN-LAST:event_mnKategoriActionPerformed

    private void mnPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnPesananMouseClicked
        // TODO add your handling code here:
        Form_Pesanan pesanan = new Form_Pesanan();
        pesanan.setLocationRelativeTo(null);
        pesanan.setVisible(true);
    }//GEN-LAST:event_mnPesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu File;
    private javax.swing.JMenu Master;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnKategori;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnPegawai;
    private javax.swing.JMenu mnPesanan;
    private javax.swing.JMenuItem mnProduk;
    private javax.swing.JMenuItem mnSupplier;
    // End of variables declaration//GEN-END:variables
}
